use krassekarossengenossen;
insert into address (id, country, state, city, street, house_number, postal_code) values (1, 'Germany', 'Berlin', 'Berlin', 'Prentice', '0211', '13599');
insert into address (id, country, state, city, street, house_number, postal_code) values (2, 'Germany', 'Hamburg', 'Hamburg', 'Dorton', '4', '20359');
insert into address (id, country, state, city, street, house_number, postal_code) values (3, 'Germany', 'Berlin', 'Berlin', 'Meadow Vale', '66277', '13347');
insert into address (id, country, state, city, street, house_number, postal_code) values (4, 'Germany', 'Hamburg', 'Hamburg', 'Hermina', '42', '22179');
insert into address (id, country, state, city, street, house_number, postal_code) values (5, 'Germany', 'Nordrhein-Westfalen', 'Mülheim an der Ruhr', 'Brentwood', '3', '45473');
insert into address (id, country, state, city, street, house_number, postal_code) values (6, 'Germany', 'Bayern', 'München', 'Schlimgen', '6715', '80686');
insert into address (id, country, state, city, street, house_number, postal_code) values (7, 'Germany', 'Nordrhein-Westfalen', 'Düsseldorf', 'Ridgeview', '00182', '40591');
insert into address (id, country, state, city, street, house_number, postal_code) values (8, 'Germany', 'Berlin', 'Berlin', 'Basil', '53', '10823');
insert into address (id, country, state, city, street, house_number, postal_code) values (9, 'Germany', 'Berlin', 'Berlin', 'Sherman', '351', '10823');
insert into address (id, country, state, city, street, house_number, postal_code) values (10, 'Germany', 'Baden-Württemberg', 'Mannheim', 'Summit', '81928', '68239');
insert into address (id, country, state, city, street, house_number, postal_code) values (11, 'Germany', 'Nordrhein-Westfalen', 'Düsseldorf', 'Merchant', '4', '40489');
insert into address (id, country, state, city, street, house_number, postal_code) values (12, 'Germany', 'Berlin', 'Berlin', 'Bashford', '71', '10409');
insert into address (id, country, state, city, street, house_number, postal_code) values (13, 'Germany', 'Sachsen', 'Dresden', 'Burrows', '97416', '01156');
insert into address (id, country, state, city, street, house_number, postal_code) values (14, 'Germany', 'Nordrhein-Westfalen', 'Düsseldorf', 'Chive', '2', '40489');
insert into address (id, country, state, city, street, house_number, postal_code) values (15, 'Germany', 'Bayern', 'Nürnberg', 'Bonner', '156', '90480');
insert into address (id, country, state, city, street, house_number, postal_code) values (16, 'Germany', 'Bayern', 'Würzburg', 'Fair Oaks', '41565', '97078');
insert into address (id, country, state, city, street, house_number, postal_code) values (17, 'Germany', 'Berlin', 'Berlin', 'Schmedeman', '95', '12683');
insert into address (id, country, state, city, street, house_number, postal_code) values (18, 'Germany', 'Berlin', 'Berlin', 'Mosinee', '1', '14199');
insert into address (id, country, state, city, street, house_number, postal_code) values (19, 'Germany', 'Berlin', 'Berlin', 'Caliangt', '5614', '12559');
insert into address (id, country, state, city, street, house_number, postal_code) values (20, 'Germany', 'Bayern', 'München', 'Lighthouse Bay', '1', '80686');
insert into address (id, country, state, city, street, house_number, postal_code) values (21, 'Germany', 'Hamburg', 'Hamburg', 'Amoth', '240', '22453');
insert into address (id, country, state, city, street, house_number, postal_code) values (22, 'Germany', 'Nordrhein-Westfalen', 'Wuppertal', 'Vermont', '5227', '42349');
insert into address (id, country, state, city, street, house_number, postal_code) values (23, 'Germany', 'Hamburg', 'Hamburg Harvestehude', 'David', '47', '20249');
insert into address (id, country, state, city, street, house_number, postal_code) values (24, 'Germany', 'Berlin', 'Berlin', 'Bluestem', '8382', '12559');
insert into address (id, country, state, city, street, house_number, postal_code) values (25, 'Germany', 'Bayern', 'München', 'Buell', '938', '80337');
insert into address (id, country, state, city, street, house_number, postal_code) values (26, 'Germany', 'Hamburg', 'Hamburg Sankt Pauli', 'Mallard', '3', '20459');
insert into address (id, country, state, city, street, house_number, postal_code) values (27, 'Germany', 'Nordrhein-Westfalen', 'Aachen', 'Southridge', '43', '52080');
insert into address (id, country, state, city, street, house_number, postal_code) values (28, 'Germany', 'Nordrhein-Westfalen', 'Aachen', 'Brentwood', '63443', '52080');
insert into address (id, country, state, city, street, house_number, postal_code) values (29, 'Germany', 'Berlin', 'Berlin', 'Loeprich', '37', '12437');
insert into address (id, country, state, city, street, house_number, postal_code) values (30, 'Germany', 'Nordrhein-Westfalen', 'Dortmund', 'Blaine', '584', '44269');
insert into address (id, country, state, city, street, house_number, postal_code) values (31, 'Germany', 'Nordrhein-Westfalen', 'Aachen', '1st', '54', '52080');
insert into address (id, country, state, city, street, house_number, postal_code) values (32, 'Germany', 'Nordrhein-Westfalen', 'Bielefeld', 'Independence', '0', '33619');
insert into address (id, country, state, city, street, house_number, postal_code) values (33, 'Germany', 'Baden-Württemberg', 'Reutlingen', 'Shasta', '6', '72768');
insert into address (id, country, state, city, street, house_number, postal_code) values (34, 'Germany', 'Berlin', 'Berlin', 'Bunting', '3', '12437');
insert into address (id, country, state, city, street, house_number, postal_code) values (35, 'Germany', 'Hamburg', 'Hamburg', 'Pine View', '6', '20359');
insert into address (id, country, state, city, street, house_number, postal_code) values (36, 'Germany', 'Nordrhein-Westfalen', 'Wuppertal', 'Schiller', '9863', '42349');
insert into address (id, country, state, city, street, house_number, postal_code) values (37, 'Germany', 'Berlin', 'Berlin', 'Lunder', '0487', '13509');
insert into address (id, country, state, city, street, house_number, postal_code) values (38, 'Germany', 'Nordrhein-Westfalen', 'Düsseldorf', 'Wayridge', '1', '40225');
insert into address (id, country, state, city, street, house_number, postal_code) values (39, 'Germany', 'Baden-Württemberg', 'Stuttgart Stuttgart-Mitte', 'Evergreen', '31273', '70180');
insert into address (id, country, state, city, street, house_number, postal_code) values (40, 'Germany', 'Nordrhein-Westfalen', 'Herne', 'Daystar', '2', '44629');
insert into address (id, country, state, city, street, house_number, postal_code) values (41, 'Germany', 'Hamburg', 'Hamburg Bramfeld', 'Dakota', '98573', '22179');
insert into address (id, country, state, city, street, house_number, postal_code) values (42, 'Germany', 'Hamburg', 'Hamburg Bramfeld', 'Towne', '997', '22179');
insert into address (id, country, state, city, street, house_number, postal_code) values (43, 'Germany', 'Sachsen', 'Dresden', 'Lukken', '583', '01462');
insert into address (id, country, state, city, street, house_number, postal_code) values (44, 'Germany', 'Schleswig-Holstein', 'Lübeck', 'Manufacturers', '86143', '23568');
insert into address (id, country, state, city, street, house_number, postal_code) values (45, 'Germany', 'Hessen', 'Frankfurt am Main', 'Arizona', '924', '60325');
insert into address (id, country, state, city, street, house_number, postal_code) values (46, 'Germany', 'Baden-Württemberg', 'Reutlingen', 'Rieder', '9', '72768');
insert into address (id, country, state, city, street, house_number, postal_code) values (47, 'Germany', 'Bremen', 'Bremen', 'Beilfuss', '4063', '28239');
insert into address (id, country, state, city, street, house_number, postal_code) values (48, 'Germany', 'Nordrhein-Westfalen', 'Wuppertal', 'Waubesa', '481', '42349');
insert into address (id, country, state, city, street, house_number, postal_code) values (49, 'Germany', 'Nordrhein-Westfalen', 'Dortmund', 'Del Sol', '93', '44369');
insert into address (id, country, state, city, street, house_number, postal_code) values (50, 'Germany', 'Bayern', 'München', 'Anniversary', '636', '80686');
insert into address (id, country, state, city, street, house_number, postal_code) values (51, 'Germany', 'Hessen', 'Frankfurt am Main', 'Becker', '8356', '60435');
insert into address (id, country, state, city, street, house_number, postal_code) values (52, 'Germany', 'Berlin', 'Berlin', 'Duke', '1', '12437');
insert into address (id, country, state, city, street, house_number, postal_code) values (53, 'Germany', 'Berlin', 'Berlin', 'Hanson', '1994', '12169');
insert into address (id, country, state, city, street, house_number, postal_code) values (54, 'Germany', 'Sachsen', 'Chemnitz', 'Scoville', '7', '09123');
insert into address (id, country, state, city, street, house_number, postal_code) values (55, 'Germany', 'Berlin', 'Berlin', 'Mandrake', '33173', '12559');
insert into address (id, country, state, city, street, house_number, postal_code) values (56, 'Germany', 'Nordrhein-Westfalen', 'Dortmund', 'Raven', '301', '44143');
insert into address (id, country, state, city, street, house_number, postal_code) values (57, 'Germany', 'Baden-Württemberg', 'Freiburg im Breisgau', 'Hudson', '9731', '79114');
insert into address (id, country, state, city, street, house_number, postal_code) values (58, 'Germany', 'Berlin', 'Berlin', 'Browning', '0824', '12103');
insert into address (id, country, state, city, street, house_number, postal_code) values (59, 'Germany', 'Berlin', 'Berlin', 'Algoma', '876', '13347');
insert into address (id, country, state, city, street, house_number, postal_code) values (60, 'Germany', 'Nordrhein-Westfalen', 'Herne', 'Logan', '65', '44629');
insert into address (id, country, state, city, street, house_number, postal_code) values (61, 'Germany', 'Sachsen-Anhalt', 'Magdeburg', '8th', '734', '39130');
insert into address (id, country, state, city, street, house_number, postal_code) values (62, 'Germany', 'Hessen', 'Hanau', 'Banding', '77462', '63456');
insert into address (id, country, state, city, street, house_number, postal_code) values (63, 'Germany', 'Bayern', 'München', 'Knutson', '8', '80995');
insert into address (id, country, state, city, street, house_number, postal_code) values (64, 'Germany', 'Nordrhein-Westfalen', 'Dortmund', 'Larry', '4', '44369');
insert into address (id, country, state, city, street, house_number, postal_code) values (65, 'Germany', 'Berlin', 'Berlin', 'Monterey', '66', '12307');
insert into address (id, country, state, city, street, house_number, postal_code) values (66, 'Germany', 'Hamburg', 'Hamburg Sankt Pauli', 'Waxwing', '049', '20459');
insert into address (id, country, state, city, street, house_number, postal_code) values (67, 'Germany', 'Hessen', 'Wetzlar', 'Merrick', '2', '35581');
insert into address (id, country, state, city, street, house_number, postal_code) values (68, 'Germany', 'Berlin', 'Berlin', 'Maple', '5834', '13088');
insert into address (id, country, state, city, street, house_number, postal_code) values (69, 'Germany', 'Nordrhein-Westfalen', 'Essen', 'Esker', '5', '45149');
insert into address (id, country, state, city, street, house_number, postal_code) values (70, 'Germany', 'Nordrhein-Westfalen', 'Essen', 'Village Green', '9', '45141');
insert into address (id, country, state, city, street, house_number, postal_code) values (71, 'Germany', 'Baden-Württemberg', 'Stuttgart', 'Nevada', '1998', '70374');
insert into address (id, country, state, city, street, house_number, postal_code) values (72, 'Germany', 'Nordrhein-Westfalen', 'Dortmund', 'Monterey', '29925', '44269');
insert into address (id, country, state, city, street, house_number, postal_code) values (73, 'Germany', 'Hessen', 'Offenbach', 'Dawn', '570', '63073');
insert into address (id, country, state, city, street, house_number, postal_code) values (74, 'Germany', 'Hessen', 'Frankfurt am Main', 'Portage', '605', '60325');
insert into address (id, country, state, city, street, house_number, postal_code) values (75, 'Germany', 'Rheinland-Pfalz', 'Mainz', 'Springview', '782', '55124');
insert into address (id, country, state, city, street, house_number, postal_code) values (76, 'Germany', 'Baden-Württemberg', 'Stuttgart', 'Wayridge', '01', '70190');
insert into address (id, country, state, city, street, house_number, postal_code) values (77, 'Germany', 'Berlin', 'Berlin', 'Northview', '23238', '10179');
insert into address (id, country, state, city, street, house_number, postal_code) values (78, 'Germany', 'Nordrhein-Westfalen', 'Duisburg', 'Judy', '085', '47139');
insert into address (id, country, state, city, street, house_number, postal_code) values (79, 'Germany', 'Bremen', 'Bremen', 'Farwell', '90635', '28355');
insert into address (id, country, state, city, street, house_number, postal_code) values (80, 'Germany', 'Sachsen', 'Chemnitz', 'Union', '7272', '09116');
insert into address (id, country, state, city, street, house_number, postal_code) values (81, 'Germany', 'Nordrhein-Westfalen', 'Bielefeld', 'Scofield', '6', '33619');
insert into address (id, country, state, city, street, house_number, postal_code) values (82, 'Germany', 'Nordrhein-Westfalen', 'Köln', 'Morrow', '63422', '50733');
insert into address (id, country, state, city, street, house_number, postal_code) values (83, 'Germany', 'Hessen', 'Frankfurt am Main', 'Fisk', '89140', '60549');
insert into address (id, country, state, city, street, house_number, postal_code) values (84, 'Germany', 'Bayern', 'Würzburg', 'Ludington', '6864', '97078');
insert into address (id, country, state, city, street, house_number, postal_code) values (85, 'Germany', 'Nordrhein-Westfalen', 'Bochum', 'Talisman', '91759', '44869');
insert into address (id, country, state, city, street, house_number, postal_code) values (86, 'Germany', 'Sachsen', 'Leipzig', 'Hallows', '090', '04288');
insert into address (id, country, state, city, street, house_number, postal_code) values (87, 'Germany', 'Sachsen', 'Chemnitz', 'Hansons', '08310', '09116');
insert into address (id, country, state, city, street, house_number, postal_code) values (88, 'Germany', 'Nordrhein-Westfalen', 'Remscheid', 'Hoepker', '90', '42897');
insert into address (id, country, state, city, street, house_number, postal_code) values (89, 'Germany', 'Bayern', 'München', 'Troy', '6853', '80686');
insert into address (id, country, state, city, street, house_number, postal_code) values (90, 'Germany', 'Sachsen-Anhalt', 'Halle', 'Merrick', '0523', '06126');
insert into address (id, country, state, city, street, house_number, postal_code) values (91, 'Germany', 'Baden-Württemberg', 'Karlsruhe', 'Bultman', '630', '76199');
insert into address (id, country, state, city, street, house_number, postal_code) values (92, 'Germany', 'Hamburg', 'Hamburg Bramfeld', 'Anthes', '7393', '22179');
insert into address (id, country, state, city, street, house_number, postal_code) values (93, 'Germany', 'Berlin', 'Berlin', 'Pierstorff', '6', '10587');
insert into address (id, country, state, city, street, house_number, postal_code) values (94, 'Germany', 'Nordrhein-Westfalen', 'Essen', 'Maple', '0062', '45356');
insert into address (id, country, state, city, street, house_number, postal_code) values (95, 'Germany', 'Bayern', 'München', 'Comanche', '6979', '80686');
insert into address (id, country, state, city, street, house_number, postal_code) values (96, 'Germany', 'Sachsen-Anhalt', 'Halle', 'Butterfield', '2239', '06126');
insert into address (id, country, state, city, street, house_number, postal_code) values (97, 'Germany', 'Hamburg', 'Hamburg', 'Dryden', '25159', '22111');
insert into address (id, country, state, city, street, house_number, postal_code) values (98, 'Germany', 'Bayern', 'Nürnberg', 'Lerdahl', '2', '90451');
insert into address (id, country, state, city, street, house_number, postal_code) values (99, 'Germany', 'Nordrhein-Westfalen', 'Bochum', 'Division', '7', '44795');
insert into address (id, country, state, city, street, house_number, postal_code) values (100, 'Germany', 'Hessen', 'Wetzlar', 'Myrtle', '27800', '35581');
